name: vit_paddy_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.1
  - numpy=1.23.5
  - pandas=1.5.3
  - pillow=9.4.0
  - scikit-learn=1.2.2
  - joblib=1.2.0
  - matplotlib=3.7.1
  - pip:
    - tensorflow==2.16.1
    - keras==3.3.3
    - protobuf==3.20.3
    - h5py==3.10.0