name: vit_paddy_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy==1.23.5
  - pandas
  - scikit-learn
  - matplotlib=3.6.2
  - tqdm
  - jupyter
  - pillow
  - pip:
      - tensorflow=2.15.0
      - keras==2.15.0
